apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redpanda-data
  namespace: {{ .Values.kafka.namespace }}
spec:
  storageClassName: {{ .Values.kafka.storage.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kafka.storage.size }}