apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: {{ .Values.kafka.namespace }}
spec:
  clusterIP: None
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: {{ .Values.kafka.redpanda.port }}
      targetPort: kafka
    - name: admin
      port: 9644
      targetPort: admin
    - name: pandaproxy
      port: {{ .Values.kafka.redpanda.pandaproxyPort }}
      targetPort: pandaproxy