apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJvbXJpd2FsbGFjaCIsInBhc3N3b3JkIjoib21yaTA1MDI2NDI5MzUiLCJlbWFpbCI6Im9tcml3YWxsYWNoMTk5MkBnbWFpbC5jb20iLCJhdXRoIjoiYjIxeWFYZGhiR3hoWTJnNmIyMXlhVEExTURJMk5ESTVNelU9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
