apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: koldavar-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /audio-to-text
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.audioToText.name }}-service
                port:
                  number: {{ .Values.services.audioToText.port }}

          - path: /input-extraction
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.inputExtraction.name }}-service
                port:
                  number: {{ .Values.services.inputExtraction.port }}

          - path: /sync-manager
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.syncManager.name }}-service
                port:
                  number: {{ .Values.services.syncManager.port }}

          - path: /text-synthesizer
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.textSynthesizer.name }}-service
                port:
                  number: {{ .Values.services.textSynthesizer.port }}
