apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.name }}
  namespace: {{ .Values.kafka.namespace }}
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    config:
      process.roles: "broker,controller"
      node.id: 0
      controller.quorum.voters: "0@{{ .Values.kafka.name }}-controller-0.{{ .Values.kafka.name }}-controller:9093"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
  entityOperator:
    topicOperator: {}
    userOperator: {}
