apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: {{ .Values.kafka.name }}-controller
  namespace: {{ .Values.kafka.namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.name }}
spec:
  replicas: 1
  roles:
    - controller
  storage:
    type: persistent-claim
    size: {{ .Values.kafka.storage }}
    deleteClaim: true
