# {{- $root := . }}
# {{- $users := list "consumer" "producer" }}
# {{- range $type := $users }}
# ---
# apiVersion: kafka.strimzi.io/v1beta2
# kind: KafkaUser
# metadata:
#   name: {{ $type }}-user
#   namespace: {{ $root.Values.kafka.namespace }}
#   labels:
#     strimzi.io/cluster: {{ $root.Values.kafka.name }}
#   annotations:
#     "meta.helm.sh/release-name": {{ $root.Values.kafka.releaseName }}
#     "meta.helm.sh/release-namespace": {{ $root.Values.kafka.releaseNamespace }}
# spec:
#   authentication:
#     type: scram-sha-512
# {{- end }}