{{- $root := . }}
{{- range $topic := $root.Values.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $topic.name }}
  namespace: {{ $root.Values.kafka.namespace }}
  labels:
    strimzi.io/cluster: {{ $root.Values.kafka.name }}
    app.kubernetes.io/managed-by: Helm
spec:
  partitions: {{ $topic.partitions }}
  replicas: {{ $topic.replicas }}
  config:
    retention.ms: {{ $topic.retentionMs }}
{{- end }}
