{{- $root := . }}
{{- range $index, $topic := .Values.topics }}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: {{ $topic.name }}
  namespace: {{ $root.Values.kafka.namespace }}
  labels:
    strimzi.io/cluster: {{ $root.Values.kafka.name }}
  annotations:
    meta.helm.sh/release-name: {{ $root.Values.kafka.releaseName }}
    meta.helm.sh/release-namespace: {{ $root.Values.kafka.releaseNamespace }}
    app.kubernetes.io/managed-by: Helm
spec:
  partitions: {{ $topic.partitions }}
  replicas: {{ $topic.replicas }}
  config:
    retention.ms: {{ $topic.retentionMs }}
{{- end }}