global:
  dockerHubSecret:
    name: dockerhub-secret
  
  security:
    allowInsecureImages: true

services:
  audioToText:
    name: audio-to-text
    enabled: true
    image: "omriwallach/koldavar:audio_to_text"
    pullPolicy: Always
    port: 8080
    replicas: 1

  inputExtraction:
    name: input-extraction
    enabled: true
    image: "omriwallach/koldavar:input_extraction"
    pullPolicy: Always
    port: 8081
    replicas: 1

  syncManager:
    name: sync-manager
    enabled: true
    image: "omriwallach/koldavar:sync_manager"
    pullPolicy: Always
    port: 8082
    replicas: 1

  textSynthesizer:
    name: text-synthesizer
    enabled: true
    image: "omriwallach/koldavar:text_synthesizer"
    pullPolicy: Always
    port: 8083
    replicas: 1

redis:
  name: redis
  enabled: true
  image: redis
  port: 8085
  targetPort: 6379


nginxIngressController:
  enabled: true

  ingressClassResource:
    name: nginx
    enabled: true

  controller:
    ingressClass: nginx

nginx-ingress-controller:
  image:
    registry: public.ecr.aws
    repository: bitnami/nginx-ingress-controller
    tag: "1.13.1-debian-12-r1"   # latest available
    pullPolicy: IfNotPresent

  defaultBackend:
    image:
      registry: public.ecr.aws
      repository: bitnami/nginx
      tag: "1.29.1-debian-12-r0"
      pullPolicy: IfNotPresent

kafka:
  name: koldavar-kafka
  version: 3.7.0
  metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "meta.helm.sh/release-name": koldavar

  replicas: 3
  storageSize: 10Gi

zookeeper:
  replicas: 3
  storageSize: 10Gi

entityOperator:
  enabled: true

strimzi-kafka-operator:
  installCRDs: false