apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: audio-to-text
  name: audio-to-text
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio-to-text
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: audio-to-text
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - image: omriwallach/koldavar:audio_to_text
        imagePullPolicy: Always
        name: audio-to-text
        resources: {}
status: {}
