apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: input-extraction
  name: input-extraction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: input-extraction
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: input-extraction
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - image: omriwallach/koldavar:input_extraction
        imagePullPolicy: Always
        name: input-extraction
        resources: {}
status: {}
