{{- if .Values.services.eventRouter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.eventRouter.name }}
spec:
  replicas: {{ .Values.services.eventRouter.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.eventRouter.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.eventRouter.name }}
    spec:
      imagePullSecrets: 
      - name: {{ .Values.global.dockerHubSecret.name }}
      containers:
        - name: {{ .Values.services.eventRouter.name }}
          image: {{ .Values.services.eventRouter.image }}
          imagePullPolicy: {{ .Values.services.eventRouter.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.eventRouter.port }}
          env:
                        # --- KAFKA CONNECTIVITY ---
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.kafka.redpanda.advertisedKafkaAddr }}:{{ .Values.kafka.redpanda.port }}"

            - name: KAFKA_TOPICS
              value: {{ join "," .Values.kafka.topics | quote }}
{{- end }}