{{- if .Values.services.eventRouter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.eventRouter.name }}
spec:
  replicas: {{ .Values.services.eventRouter.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.eventRouter.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.eventRouter.name }}
    spec:
      imagePullSecrets: 
      - name: {{ .Values.global.dockerHubSecret.name }}
      containers:
        - name: {{ .Values.services.eventRouter.name }}
          image: {{ .Values.services.eventRouter.image }}
          imagePullPolicy: {{ .Values.services.eventRouter.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.eventRouter.port }}
          env:
            - name: SERVICE_NAME
              value: {{ .Values.services.eventRouter.name | quote }}

            - name: HTTP_PORT
              value: {{ .Values.services.eventRouter.port | quote }}

            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ printf "%s:%d" .Values.kafka.redpanda.advertisedKafkaAddr .Values.kafka.redpanda.port | quote }}

            # ------------------------------------------------
            # ROUTER TARGETS (DERIVED FROM SERVICE NAME + PORT)
            # ------------------------------------------------
            - name: ROUTER_BASEURL_INPUT_EXTRACTION
              value: {{ printf "http://%s-service:%d" .Values.services.inputExtraction.name .Values.services.inputExtraction.port | quote }}

            - name: ROUTER_BASEURL_AUDIO_TO_TEXT
              value: {{ printf "http://%s-service:%d" .Values.services.audioToText.name .Values.services.audioToText.port | quote }}

            - name: ROUTER_BASEURL_TEXT_SYNTHESIZER
              value: {{ printf "http://%s-service:%d" .Values.services.textSynthesizer.name .Values.services.textSynthesizer.port | quote }}

            - name: ROUTER_BASEURL_SYNC_MANAGER
              value: {{ printf "http://%s-service:%d" .Values.services.syncManager.name .Values.services.syncManager.port | quote }}

            {{- if .Values.services.tts.enabled }}
            - name: ROUTER_BASEURL_TTS
              value: {{ printf "http://%s-service:%d" .Values.services.tts.name .Values.services.tts.port | quote }}
            {{- end }}
{{- end }}