apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: audio-to-text
  name: audio-to-text-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: audio-to-text
status:
  loadBalancer: {}
