apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: input-extraction
  name: input-extraction-service
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: input-extraction
status:
  loadBalancer: {}
