apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sync-manager
  name: sync-manager-service
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: sync-manager
status:
  loadBalancer: {}
