apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: text-synthesizer
  name: text-synthesizer-service
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: text-synthesizer
status:
  loadBalancer: {}
