apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: koldavar
    releaseName: koldavar
    namespace: default
    repo: "file://../helm"
    valuesFile: ../helm/koldavar/values.yaml
    includeCRDs: true
