name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  docker-images:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Debug event payload
        run: |
          echo "Workflow Run Name: ${{ github.event.workflow_run.name }}"
          echo "Workflow Run Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow Run Branch: ${{ github.event.workflow_run.head_branch }}"

      - name: Checkout code for EXACT commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push with Docker Compose
        run: |
          docker compose -f ./docker/docker-compose.yml build
          docker compose -f ./docker/docker-compose.yml push
